{exec} = require 'child_process'
coffee = require 'coffee-script'
util = require 'util'
yui = require 'yui-compressor'
fs = require 'fs'

FILENAME = 'jubiol'
FILES = [
  'kwing/lib/vector.coffee',
  'kwing/lib/array.coffee',
  'kwing/lib/timer.coffee',
  'kwing/lib/jukebox.coffee',
  'src/main.coffee',
  'src/sprite.coffee',
  'src/player.coffee',
  'src/bullet.coffee',
  'src/state.coffee',
  'src/level.coffee',
  'src/stage.coffee',
  'src/scene.coffee'
]
HTMLFILE = 'index.html'


task 'compile', 'compile and minify Osushi.', (options) ->
  for file, i in FILES
    util.log "load [#{i}] #{file}"
    FILES[i] = fs.readFileSync(file, "utf8")
  util.log "compile CoffeeScript -> JavaScript"
  js = coffee.compile FILES.join "\n"
  util.log "minify (yui-compressor)"
  yui.compile js, (err, res) ->
    if err?
      util.debug err
    fs.writeFileSync "#{FILENAME}.min.js", res, "utf8"
    util.log "complete"
